# The URL the site will be built for
base_url = "https://hadziqm.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "terminus"


taxonomies = [
    { name = "tech", feed = true },
    { name = "domain", feed = true, paginate_by = 5 },
]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here


main_menu = [
    # { name = "blog", url = "blog", trailing_slash = true },
    # { name = "archive", url = "archive", trailing_slash = true },
    # { name = "tags", url = "tags", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
    { name = "github", url = "https://github.com/ebkalderon/terminus", new_tab = true },
]

socials = [
    { name = "email", url = "mailto:dimascrazz@gmail.com" },
    { name = "github", url = "https://github.com/hadziqm" },
    # { name = "linkedin", url = "https://www.linkedin.com/in/HadziqmM" },
    # { name = "mastodon", url = "https://hachyderm.io/@ebkalderon" },
    # { name = "keyoxide", url = "https://keyoxide.org/d5ad5bd47835b0f0b0c3046c00ab4c0942dcba25" },
]
